### ISSUE TITLE
Divided by 0 should be handled gracefully.

### ISSUE THREAD

**Issue by sskant786** [2020MT93167/Calculator#10]
Division component should handle the Exception gracefully when a user tries to divide any number with zero.

**Comment by sahil5655** [comment]
Ok will work on it.

**Comment by sahil5655** [comment]
![image](https://user-images.githubusercontent.com/18023069/114496786-52716280-9c3e-11eb-9dc5-6115d6a7ac8f.png)
Handled. Closing the issue
